/*
 * generated by Xtext 2.16.0
 */
package org.sbelei.archide.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class ProjectWbsWebModule extends AbstractProjectWbsWebModule {
}
