/*
 * generated by Xtext 2.16.0
 */
package org.sbelei.archide


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ProjectWbsRuntimeModule extends AbstractProjectWbsRuntimeModule {
}
