/*
 * generated by Xtext 2.16.0
 */
package org.sbelei.archide


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ProjectWbsStandaloneSetup extends ProjectWbsStandaloneSetupGenerated {

	def static void doSetup() {
		new ProjectWbsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
